### ISSUE TITLE
The solution is not okay for protoc version <3

### ISSUE THREAD

**Issue by xtzd** [adeelz92/Install-Caffe-on-Ubuntu-16.04-Python-3#1]
### When doing as what you represent,  I can not do "make pytest", also when "import caffe",it does not go through at all.

Here is the error reporting situation:
"EEEEEEEEEE
======================================================================
ERROR: test_solver (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_solver
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/jack/.local/install/caffe/python/caffe/test/test_solver.py", line 7, in <module>
    import caffe
  File "caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: dynamic module does not define init function (init_caffe)
....
.....
......
.......
Ran 10 tests in 0.000s

FAILED (errors=10)
Makefile:536: recipe for target 'pytest' failed
make: *** [pytest] Error 1"

None of the 10 test files can be compiled.

**Comment by xtzd** [comment]
I searched for a same case: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/caffe-users/_Iydbi8T-GQ/y2M3vYFOCAAJ

but no solution for protobuf version <3.0.0.

But anyway thanks for your tutorial. I wonder what is the 'protoc --version' in your OS.

**Comment by adeelz92** [comment]
Hi, the protoc version on my OS is 3.5.0.
Also this tutorial is for Python3 and if you are installing caffe for Python3 than it should use usr/lib/python3.* to run unit tests. In your case, it is using python2.7.
