### ISSUE TITLE
create build

### ISSUE THREAD

**Issue by leo2105** [adeelz92/Install-Caffe-on-Ubuntu-16.04-Python-3#3]
I was trying your tutorial but I got the problem of 

compilation terminated.
Makefile:591: recipe for target '.build_release/src/caffe/layer_factory.o' failed
make: *** [.build_release/src/caffe/layer_factory.o] Error 1

I solved it creating build, cd build, cmake ..
and then 
make all & make install & make runtest & make pycaffe

beside that, everything great!

**Comment by adeelz92** [comment]
Thanks for the update
