### ISSUE TITLE
About CUDA

### ISSUE THREAD

**Issue by HanyaoYang1** [adeelz92/Install-Caffe-on-Ubuntu-16.04-Python-3#4]
Hi, I want to ask can I use this guide in Ubuntu 18.04? And why you don't make any change in the Makefile.config file about CUDA? But if you want to build caffe on GPU,you need CUDA.

**Comment by adeelz92** [comment]
You can use this guide on Ubuntu 18.04 as well. We don't need to make any changes in the makefile because by default it builds for Cuda. If you want to build without cuda you can uncomment the line USE_CPU_only. As long as this line is commented, the caffe will build with CUDA.
